version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: run_server_debug
    container_name: social-api
    ports:
      - "5694:5694"
    volumes:
      - ./:/app/
    environment:
      - PYTHONUNBUFFERED=1
      - VIRTUAL_HOST=avito.net
      - VIRTUAL_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 

networks:
  default:
    name: im
    external: true