routes:
# Получение информации об авторизованном пользователе
  - path: /core/v1/accounts/self
    methods:
      - method: GET
        response:
          email: "example@domain.com"
          id: 94235311
          name: "Петр"
          phone: 71112223344
          phones:
            - "71112223344"
          profile_url: "https://avito.ru/user/7d04cdc3a12726eee72c6851c953ac54/profile" 
