routes:
# Получение информации об авторизованном пользователе
  - path: /core/v1/accounts/self
    methods:
      - method: GET
        response:
          email: example@domain.com
          id: "{$random_code}"
          name: Петр
          phone: "+79994{$random_code}"
          phones:
          - '+79053{$random_code}'
          profile_url: https://avito.ru/user/7d04cdc3a12726eee72c6851c953ac54/profile
  
