routes:
# Отправка ответа на отзыв
  - path: /ratings/v1/answers
    methods:
      - method: POST
        content_type: application/json
        request_schema:
          type: object
          properties:
            message:
              type: string
              description: "Ответ на отзыв"
            reviewId:
              type: integer
              description: "Идентификатор отзыва"
          required: [message, reviewId]
        response:
          createdAt: 
            value: "{$current_timestamp}" 
            type: integer
          id: 
            value: "{$random_code}"
            type: integer

# Запрос на удаление ответа на отзыв
  - path: /ratings/v1/answer/{reviewId}
    methods:
      - method: DELETE
        content_type: application/json
        response:
          success: true

# Получение списка активных отзывов на пользователя с пагинацией
  - path: /ratings/v1/reviews
    methods:
      - method: GET
        content_type: application/json
        response:
          reviews:
            - answer:
                createdAt: 
                  value: "{$current_timestamp}" 
                  type: integer
                id: 
                  value: "{$random_code}"
                  type: integer
                reject_reasons:
                  - id: 
                      value: "{$random_code}"
                      type: integer
                    title: "Нецензурная лексика"
                status: "published"
                text: "Спасибо за отзыв!"
              canAnswer: true
              createdAt: 
                value: "{$current_timestamp}"
                type: integer
              extraParams:
                vin: "4Y1SL65848Z411439"
              id:
                value: "{$random_code}"
                type: integer
              images:
                - number: 1
                  sizes:
                    - size: "100x100"
                      url: "http://img.avito.ru/100x100/4Y1SL65848Z411439.jpg"
              item:
                id:
                  value: "{$random_code}"
                  type: integer
                title: "Автомобиль 2020-го года"
              score: 5
              sender:
                name: "Владимир"
              stage: "fell_through"
              text: "Отличный продавец! Рекомендую :)"
              usedInScore: true
          total: 35
